name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ x86 ]
        python_version: [ '3.10' ]
        exclude:
          - target: aarch64
            python_version: pypy-3.7
          - target: aarch64
            python_version: pypy-3.8
          - target: aarch64
            python_version: pypy-3.9
          - target: aarch64
            python_version: pypy-3.10
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          repository: 'jawah/qh3'
      - uses: actions/setup-python@v5
        if: matrix.python_version != '3.13t'
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x86
      - uses: ilammy/setup-nasm@v1
      - name: Set up Clang (Cygwin)
        run: choco install llvm -y
      - name: Build wheels (normal)
        uses: PyO3/maturin-action@v1
        env:
          XWIN_VERSION: 16  # fix for "no cab file specified by MSI" ...?
          UNSAFE_PYO3_SKIP_VERSION_CHECK: 1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist
          sccache: 'true'
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist
